import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "./common.ts";

// Checked-in generated header: Arduino compiles exactly the reviewed local asset.
const base = join(ROOT, "libraries/SurfaceDevice/src");
const html = readFileSync(join(base, "writer/index.html"), "utf8");
const header = `// Generated by node --run writer:page from writer/index.html.\n#pragma once\nnamespace surface::device {\ninline constexpr char writerPage[] = R"WRITER_PAGE(${html})WRITER_PAGE";\n} // namespace surface::device\n`;
const path = join(base, "WriterPage.h");
if (process.argv.includes("--check")) {
  if (readFileSync(path, "utf8") !== header) {
    throw new Error("WriterPage.h is stale; run node --run writer:page");
  }
} else {
  writeFileSync(path, header);
}
